
version: "3"

services:

  #Postgres
  mydb:
    container_name: mydb
    build: ./postgres
    networks:
      - appnet
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres


  # app
  myapp:
    container_name: myapp
    build: ./myapp

    networks:
      - appnet
    ports:
      - "5000:5000"

    environment:
      #Conexion a la BDD con usuario restrictivo
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSW}
      POSTGRES_HOST: mydb
      POSTGRES_PORT: 5432



networks:
  appnet:
    driver: bridge
